# Generated by Django 2.0.5 on 2018-05-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_panel', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.CharField(help_text='Введіть питання, яке буде відображатися під час тесту', max_length=2000, verbose_name='Питання')),
                ('question_first_answer_content', models.CharField(help_text='Варіант відповіді під літерою А', max_length=450, verbose_name='А')),
                ('question_first_answer_state', models.BooleanField(default=False, help_text='Показчик чи є відповідь вірною', verbose_name='Правильна відповідь')),
                ('question_second_answer_content', models.CharField(help_text='Варіант відповіді під літерою А', max_length=450, verbose_name='Б')),
                ('question_second_answer_state', models.BooleanField(default=False, help_text='Показчик чи є відповідь вірною', verbose_name='Правильна відповідь')),
                ('question_third_answer_content', models.CharField(help_text='Варіант відповіді під літерою А', max_length=450, verbose_name='В')),
                ('question_third_answer_state', models.BooleanField(default=False, help_text='Показчик чи є відповідь вірною', verbose_name='Правильна відповідь')),
                ('question_fourth_answer_content', models.CharField(help_text='Варіант відповіді під літерою А', max_length=450, verbose_name='Г')),
                ('question_fourth_answer_state', models.BooleanField(default=False, help_text='Показчик чи є відповідь вірною', verbose_name='Правильна відповідь')),
                ('question_fifth_answer_content', models.CharField(help_text='Варіант відповіді під літерою А', max_length=450, verbose_name='Д')),
                ('question_fifth_answer_state', models.BooleanField(default=False, help_text='Показчик чи є відповідь вірною', verbose_name='Правильна відповідь')),
                ('question_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Discipline', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Всі питання',
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=200, verbose_name='Назва тесту')),
                ('quiz_description', models.TextField(blank=True, help_text='Опис про тест та його питання', verbose_name='Опис тесту')),
                ('quiz_single_attempt', models.BooleanField(default=False, help_text='Якщо так, студент матиме лише одну спробу.Незареєстрованні студенти не зможуть користуватися тестом (іспитом)', verbose_name='Лише одна спроба')),
                ('quiz_discipline', models.ForeignKey(help_text='Предмет з якого складається тест', null=True, on_delete=django.db.models.deletion.CASCADE, to='control_panel.Discipline', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
                'db_table': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_quiz',
            field=models.ManyToManyField(to='quiz_app.Quiz', verbose_name='Тест'),
        ),
    ]
