# Generated by Django 2.0.2 on 2018-03-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField()),
                ('question_answers', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Всі питання',
                'db_table': 'Questions',
            },
        ),
    ]
