# Generated by Django 2.1.7 on 2019-03-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted', models.BooleanField(default=False, help_text='Відмітьте, якщо студент має доступ до складання тесту', verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Допуск',
                'verbose_name_plural': 'Допуски',
                'db_table': 'accesses',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Текст відповіді')),
                ('is_true', models.BooleanField(default=False, help_text='Вибрати, якщо питання є вірним', verbose_name='Вірне')),
            ],
            options={
                'verbose_name': 'Відповідь',
                'verbose_name_plural': 'Відповіді',
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.CharField(help_text='Введіть питання, яке буде відображатися під час тесту', max_length=2000, verbose_name='Питання')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Всі питання',
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=200, verbose_name='Назва тесту')),
                ('quiz_description', models.TextField(blank=True, help_text='Опис про тест та його питання', verbose_name='Опис тесту')),
                ('quiz_single_attempt', models.BooleanField(default=False, help_text='Якщо так, студент матиме лише одну спробу.Незареєстрованні студенти не зможуть користуватися тестом (іспитом)', verbose_name='Лише одна спроба')),
                ('quiz_time', models.CharField(default='10:00', max_length=5, verbose_name='Час на складання у форматі - 03:00')),
                ('quiz_discipline', models.ForeignKey(help_text='Предмет з якого складається тест', null=True, on_delete=django.db.models.deletion.CASCADE, to='control_panel.Discipline', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
                'db_table': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField(editable=False, verbose_name='Відповіді студента')),
                ('date_time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час складання тесту')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='control_panel.Student', verbose_name='Студент')),
                ('test', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результати',
                'db_table': 'Results',
            },
        ),
        migrations.CreateModel(
            name='StartingQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endTestTime', models.IntegerField(verbose_name='Время конца теста')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz', verbose_name='Тест')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Student', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Названня білету')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Білет',
                'verbose_name_plural': 'Білети',
                'db_table': 'tickets',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='ticket',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_app.Ticket', verbose_name='Білет за яким був складений тест'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_app.Ticket', verbose_name='Білет'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Question', verbose_name='Питання'),
        ),
        migrations.AddField(
            model_name='access',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='access',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Student', verbose_name='Студент'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('test', 'student')},
        ),
    ]
