# Generated by Django 2.1.7 on 2019-03-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_auto_20190327_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('Залік/Екзамен', 'Залік/Екзамен'), ('Контрольна робота', 'Контрольна робота')], default='Контрольна робота', max_length=200, verbose_name='Тип роботи'),
        ),
    ]
