# Generated by Django 2.0.2 on 2018-03-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0006_auto_20180227_2003'),
        ('quiz_app', '0002_auto_20180313_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=200, verbose_name='Назва тесту')),
                ('quiz_description', models.TextField(blank=True, help_text='Опис про тест та його питання', verbose_name='Опис тесту')),
                ('quiz_single_attemp', models.BooleanField(default=False, help_text='Якщо так, студент матиме лише одну спробу.Незареєстрованні студенти не зможуть користуватися тестом (іспитом)')),
                ('quiz_discipline', models.ForeignKey(help_text='Предмет з якого складається тест', null=True, on_delete=django.db.models.deletion.CASCADE, to='control_panel.Discipline', verbose_name='Предмет')),
            ],
            options={
                'db_table': 'Quizzes',
                'verbose_name_plural': 'Тести',
                'verbose_name': 'Тест',
            },
        ),
    ]
