# Generated by Django 2.1.1 on 2018-09-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_auto_20180903_1120'),
        ('quiz_app', '0002_result'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('test', 'student')},
        ),
    ]
