# Generated by Django 2.1.3 on 2018-12-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_auto_20180925_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
            ],
            options={
                'verbose_name': 'Тип питання',
                'verbose_name_plural': 'Типи питання',
                'db_table': 'question_types',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_time',
            field=models.CharField(default='10:00', max_length=5, verbose_name='Час на складання у форматі - 03:00'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.QuestionType', verbose_name='Тип питання'),
        ),
    ]
