# Generated by Django 2.0.2 on 2018-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_single_attemp',
            field=models.BooleanField(default=False, help_text='Якщо так, студент матиме лише одну спробу.Незареєстрованні студенти не зможуть користуватися тестом (іспитом)', verbose_name='Лише одна спроба'),
        ),
    ]
