# Generated by Django 2.1.7 on 2019-02-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_auto_20181203_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
