# Generated by Django 2.0.2 on 2018-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_auto_20180313_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_title',
        ),
        migrations.AddField(
            model_name='question',
            name='question_content',
            field=models.CharField(default=1, help_text='Введіть питання, яке буде відображатися під час тесту', max_length=2000, verbose_name='Питання'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_quiz',
            field=models.ManyToManyField(to='quiz_app.Quiz', verbose_name='Тест'),
        ),
    ]
