# Generated by Django 2.0.2 on 2018-03-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_auto_20180313_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_single_attemp',
            new_name='quiz_single_attempt',
        ),
    ]
