# Generated by Django 2.1.7 on 2019-02-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_auto_20190219_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_fifth_answer_content',
            field=models.CharField(blank=True, help_text='Варіант відповіді під літерою А', max_length=450, verbose_name='Д'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_fifth_answer_state',
            field=models.BooleanField(blank=True, default=False, help_text='Показчик чи є відповідь вірною', verbose_name='Правильна відповідь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_first_answer_content',
            field=models.CharField(blank=True, help_text='Варіант відповіді під літерою А', max_length=450, verbose_name='А'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_first_answer_state',
            field=models.BooleanField(blank=True, default=False, help_text='Показчик чи є відповідь вірною', verbose_name='Правильна відповідь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_fourth_answer_content',
            field=models.CharField(blank=True, help_text='Варіант відповіді під літерою А', max_length=450, verbose_name='Г'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_fourth_answer_state',
            field=models.BooleanField(blank=True, default=False, help_text='Показчик чи є відповідь вірною', verbose_name='Правильна відповідь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_second_answer_content',
            field=models.CharField(blank=True, help_text='Варіант відповіді під літерою А', max_length=450, verbose_name='Б'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_second_answer_state',
            field=models.BooleanField(blank=True, default=False, help_text='Показчик чи є відповідь вірною', verbose_name='Правильна відповідь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_third_answer_content',
            field=models.CharField(blank=True, help_text='Варіант відповіді під літерою А', max_length=450, verbose_name='В'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_third_answer_state',
            field=models.BooleanField(blank=True, default=False, help_text='Показчик чи є відповідь вірною', verbose_name='Правильна відповідь'),
        ),
    ]
