# Generated by Django 2.0.2 on 2018-03-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_auto_20180313_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_title', models.CharField(max_length=200, verbose_name='Відповідь')),
                ('answer_is_correct', models.BooleanField(default=False, help_text='Позначення, що відповідь на питання є вірною', verbose_name='Правильна відповідь? ')),
                ('answer_question', models.ForeignKey(help_text='Питання до якого відноситься відповідь', on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Question', verbose_name='Питання')),
            ],
            options={
                'db_table': 'Answers',
                'verbose_name_plural': 'Відповіді до питаннь',
                'verbose_name': 'Відповідь до питання',
            },
        ),
    ]
