# Generated by Django 2.1.7 on 2019-03-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_auto_20190325_0930'),
        ('quiz_app', '0006_auto_20190219_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted', models.BooleanField(default=False, help_text='Відмітьте, якщо студент має доступ до складання тесту', verbose_name='Доступ')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz', verbose_name='Тест')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Допуск',
                'verbose_name_plural': 'Допуски',
                'db_table': 'accesses',
            },
        ),
    ]
