# Generated by Django 2.1.7 on 2019-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_start_time',
            field=models.IntegerField(default=0),
        ),
    ]
