# Generated by Django 2.1.7 on 2019-03-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('quiz_app', '0007_access_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Білет', 'verbose_name_plural': 'Білети'},
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
    ]
