# Generated by Django 2.1.7 on 2019-03-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_auto_20190311_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_quiz',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='question_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_app.Ticket', verbose_name='Білет'),
        ),
    ]
