# Generated by Django 2.1.7 on 2019-03-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_quiz_quiz_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_start_time',
        ),
    ]
