# Generated by Django 2.1.7 on 2019-03-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_auto_20190325_0930'),
        ('quiz_app', '0009_remove_quiz_quiz_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartingQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endTestTime', models.IntegerField(verbose_name='Время конца теста')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz', verbose_name='Тест')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Student', verbose_name='Студент')),
            ],
        ),
    ]
