# Generated by Django 2.0.2 on 2018-03-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_quiz_quiz_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_questions',
        ),
    ]
