# Generated by Django 2.1.7 on 2019-03-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_auto_20190311_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_discipline',
        ),
    ]
