# Generated by Django 2.0.2 on 2018-03-20 09:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0010_remove_quiz_quiz_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_answers',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
