# Generated by Django 2.1.7 on 2019-03-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0012_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_fifth_answer_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_fifth_answer_state',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_first_answer_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_first_answer_state',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_fourth_answer_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_fourth_answer_state',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_second_answer_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_second_answer_state',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_third_answer_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_third_answer_state',
        ),
    ]
