# Generated by Django 2.1.7 on 2019-03-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0014_auto_20190311_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Відповідь', 'verbose_name_plural': 'Відповіді'},
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
    ]
