# Generated by Django 2.1.1 on 2018-09-03 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default=None, max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедри',
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'db_table': 'Disciplines',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=3, verbose_name='Кількість спроб')),
                ('first_attempt_mark', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Оцінка за першу спробу')),
                ('second_attempt_mark', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Оцінка за другу спробу')),
                ('third_attempt_mark', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Оцінка за третю спробу')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Discipline', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Оцінка',
                'verbose_name_plural': 'Оцінки',
                'db_table': 'Marks',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_active', models.BooleanField(default=True)),
                ('student_full_name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='ПІБ')),
                ('student_university_group', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Группа')),
                ('student_faculty', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Факультет або ВНЗ')),
                ('student_grade', models.IntegerField(blank=True, default=None, null=True, verbose_name='Курс')),
                ('student_state', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Статус')),
                ('student_notes', models.TextField(blank=True, default=None, null=True, verbose_name='Примітки')),
                ('student_marks', models.ManyToManyField(related_name='_student_student_marks_+', to='control_panel.Mark', verbose_name='Оцінки')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_full_name', models.CharField(default=None, max_length=200, verbose_name='ПІБ')),
                ('teacher_check_tests', models.BooleanField(default=False, verbose_name='Приймає контрольні')),
                ('teacher_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
                'db_table': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='TeacherRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_rank', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Звання')),
            ],
            options={
                'verbose_name': 'Звання викладача',
                'verbose_name_plural': 'Звання викладачів',
                'db_table': "Teacher's ranks",
            },
        ),
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troop_id', models.IntegerField(default=None, verbose_name='Номер взводу')),
                ('troop_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Department', verbose_name='Кафедра')),
                ('troop_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Teacher', verbose_name='Куратор')),
                ('troop_head_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.TeacherRank', verbose_name='Звання Куратора')),
            ],
            options={
                'verbose_name': 'Взвод',
                'verbose_name_plural': 'Взводи',
                'db_table': 'Troops',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.TeacherRank', verbose_name='Звання'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
