# Generated by Django 2.0.2 on 2018-05-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Discipline', verbose_name='Предмет')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz', verbose_name='Назва тесту')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Student', verbose_name='Студент')),
            ],
            options={
                'verbose_name_plural': 'Оцінки',
                'db_table': 'Marks',
                'verbose_name': 'Оцінка',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'discipline', 'quiz')},
        ),
    ]
