# Generated by Django 2.1.1 on 2018-09-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_app', '0001_initial'),
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz', verbose_name='Назва тесту'),
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.Student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='discipline_department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Department', verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Teacher', verbose_name='Голова'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_head_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.TeacherRank', verbose_name='Звання голови'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'discipline', 'quiz')},
        ),
    ]
