# Generated by Django 2.0.2 on 2018-04-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '__first__'),
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_quizzes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz'),
            preserve_default=False,
        ),
    ]
