# Generated by Django 2.1.3 on 2018-12-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_auto_20180903_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='attempts',
        ),
    ]
