# Generated by Django 2.1.7 on 2019-03-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_auto_20190326_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='troop_commander',
            field=models.BooleanField(default=False, verbose_name='Командир'),
        ),
    ]
