# Generated by Django 2.0.2 on 2018-04-24 09:35

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_student_student_quizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_quizzes',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
