# Generated by Django 2.0.2 on 2018-05-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_auto_20180515_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_quizzes',
        ),
    ]
