# Generated by Django 2.0.2 on 2018-05-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_remove_student_student_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_marks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Mark', verbose_name='Оцінки'),
            preserve_default=False,
        ),
    ]
