# Generated by Django 2.1.7 on 2019-03-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_remove_mark_attempts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'ПМК', 'verbose_name_plural': 'ПМК'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_marks',
        ),
        migrations.AddField(
            model_name='student',
            name='student_troop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.Troop', verbose_name='Взвод'),
        ),
    ]
