# Generated by Django 2.0.2 on 2018-04-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_auto_20180424_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_quizzes',
        ),
    ]
