# Generated by Django 2.1.7 on 2019-04-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_presence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
