# Generated by Django 2.0.2 on 2018-05-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_student_student_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_marks',
        ),
        migrations.AddField(
            model_name='student',
            name='student_marks',
            field=models.ManyToManyField(related_name='_student_student_marks_+', to='control_panel.Mark', verbose_name='Оцінки'),
        ),
    ]
