# Generated by Django 2.0.2 on 2018-04-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0005_student_student_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_quizzes',
        ),
    ]
