# Generated by Django 2.1.7 on 2019-04-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0005_remove_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_faculty',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Факультет або ВНЗ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_university_group',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Группа'),
        ),
    ]
