# Generated by Django 2.0.2 on 2018-03-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0007_auto_20180320_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Логін студента'),
        ),
    ]
