# Generated by Django 2.0.2 on 2018-03-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0008_auto_20180320_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='active',
        ),
    ]
